lexik_jwt_authentication:
    secret_key: '%env(resolve:JWT_SECRET_KEY)%'
    public_key: '%env(resolve:JWT_PUBLIC_KEY)%'
    pass_phrase: '%env(JWT_PASSPHRASE)%'
    # Durée de validité du jeton : 8 h (un service). Un « refresh token » sera ajouté avec l'app mobile.
    token_ttl: 28800
